### ISSUE TITLE
Z-Index of onscreen keyboard

### ISSUE THREAD

**Issue by pratikkabade** [vidhanshu/aicte#34]
On search bar keyboard appers to be behind the modal.

![image](https://user-images.githubusercontent.com/76637730/191280815-a3c6574d-0492-48ae-919f-2a122df49647.png)

**Comment by pratikkabade** [comment]
For changes should I use master branch itself?

**Comment by vidhanshu** [comment]
You can't directly push to master
create new branch and by pushing your code create Pull Request

**Comment by pratikkabade** [comment]
#35 css part is fixed but you may still face typing issue because of separate rendering in `index.html`

**Comment by vidhanshu** [comment]
@pratikkabade yes that's because. It was just a prototype website.
